AP-4158 Add virus/malware scanning using ClamAV
- Configure hosted environment container for clamav
- Add clamav to docker-compose.yml for testing purposes
- Add clamav configuration for CI
  Use service image and step to install clamav container
  and client

  As well as having a "service" running the clamav image
  used in production, we need to open the expected port
  on that image so a client can communicate with it in
  the test container/executor itself.

  Note that not doing this can result in false positives
  as the #virus_found? method returns true if there is
  any error, not necessarily from virus existing. An additional
  test will be added to ensure this does not occur.

  The following error will return `#virus_found? true`
  ```
  ERROR: Could not connect to clamd on localhost: Connection refused
  ```

  local configuration to ensure the expected port, 3310, will be
  added to the repos setup and readme

- Add uploader to malware_scan_results
  So we audit all attempts to upload a file

- Amend script to modify TCPSocket and TCPAddr
  For both security and to emulate production like environments
  configure local `clamd` install to listen on specific configured
  port expected by app.

  This allows the port to be changed by changing the CLAMD_TCP_SOCKET var
  and rerunning the script - `bin/install_clamav_on_mac`.